#!/usr/bin/env bash
# Generated by scripts/setup_ollama_claude.sh
# Usage:
#   source scripts/claude_ollama_env.sh
#   claude --model qwen3-coder

export ANTHROPIC_AUTH_TOKEN=ollama
export ANTHROPIC_API_KEY=""
export ANTHROPIC_BASE_URL=http://127.0.0.1:11434
